### ISSUE TITLE
Incorrect default value for `start` when `step` is negative in the slice selector

### ISSUE THREAD

**Issue by lukasz05** [rsonquery/rsonpath#546]
### Package

Library

### Describe the bug

According to [RFC 9535](https://www.rfc-editor.org/rfc/rfc9535#tbl-slice-start-end), the default value for `start` depends on the sing of `step` and is `len - 1` when `step < 0`. The JSONPath parser always uses `0` as the default value for `start`.

### Minimal Reproducible Example

```rust
let query1 = rsonpath_syntax::parse("$[::-1]").unwrap();
let query2 = rsonpath_syntax::parse("$[0::-1]").unwrap();
assert_ne!(query1, query2);
```

### Expected behavior

`$[::-1]` and `$[0::-1]` are different queries, so their ASTs generated by the parser can't be equal.
The `start` field of the `Slice` struct should probably be of type `Option<Index>` and set to `None` if the value is omitted, just like the `end` field.

### Version of the release

v0.9.1

### Rust version

1.80.1

### Target triple

aarch64-apple-darwin

### Features enabled

default

**Comment by V0ldek** [comment]
This is indeed a bug.

For `$[::-1]` the correct output should be the same as for `$[-1::-1]`, so a start value of `FromEnd(JsonNonZeroUInt(1))`.
