### ISSUE TITLE
Add Rc to Arc feature in async and multithread context

### ISSUE THREAD

**Issue by azoyan** [rsonquery/rsonpath#620]
Is it possible to add feature to replace Rc in inner structures to Arc to use in async context?
```rust
pub struct RateLimitBodyJsonPath {
    pub jsonpath: Vec<RsonpathEngine>
}
```

```
error[E0277]: `Rc<StringPattern>` cannot be shared between threads safely
   --> core/src/rule/mod.rs:339:21
    |
339 | /                     tokio::spawn(async move {
340 | |                         let mut guard = RULES.write().await;
341 | |                         guard.remove(tenant_clone.as_str());
342 | |                     });
    | |______________________^ `Rc<StringPattern>` cannot be shared between threads safely
    |
    = help: within `[(Rc<StringPattern>, rsonpath::automaton::State); 2]`, the trait `Sync` is not implemented for `Rc<StringPattern>`, which is required by `{async block@core/src/rule/mod.rs:339:34: 339:44}: Send`
    = note: required because it appears within the type `(Rc<StringPattern>, rsonpath::automaton::State)`
    = note: required because it appears within the type `[(Rc<StringPattern>, rsonpath::automaton::State); 2]`
    = note: required for `smallvec::SmallVecData<[(Rc<StringPattern>, rsonpath::automaton::State); 2]>` to implement `Sync`
```

**Comment by V0ldek** [comment]
It's possible, but after the holiday break 😄

For now as a workaround you can make it `Send` and `Sync` with a wrapper and `unsafe`
 
 ```rust
 struct RsonpathEngineWrap(RsonpathEngine);
 
 unsafe impl Send for RsonpathEngineWrap {}
 unsafe impl Sync for RsonpathEngineWrap {}
 ```
 
 This is safe because
1. `RsonpathEngine` is not `Clone`
2. We never clone the `Rc`s inside the `Automaton` after construction and always pass the strings by reference.

In other words the `Rc`s are never cloned after the engine is built.

**Comment by azoyan** [comment]
Make release please)

**Comment by azoyan** [comment]
> Make release please) 9.3

@V0ldek

**Comment by V0ldek** [comment]
Pinging me in the morning of Christmas Eve is unlikely to actually speed up a release 😛 

If you're blocked, point your `rsonpath-lib` to the latest commit:

```toml
rsonpath_lib = { git = "https://github.com/rsonquery/rsonpath.git", rev = "37e907684173637191e3b42ea525d9a5ef0ab208" }
```

**Comment by azoyan** [comment]
> Pinging me in the morning of Christmas Eve is unlikely to actually speed up a release 😛
> 
> If you're blocked, point your `rsonpath-lib` to the latest commit:
> 
> ```toml
> rsonpath-lib = { git = "https://github.com/rsonquery/rsonpath.git", rev = "37e907684173637191e3b42ea525d9a5ef0ab208" }
> ```

Yes, I already use something like this, but for work I need to use the release version.

Ok. I will be waiting. 

 🎅🏻 🎄 Merry Christmas!  🎁 ☃️

**Comment by azoyan** [comment]
Thank you
