### ISSUE TITLE
Make logs depends on feature or env_logger

### ISSUE THREAD

**Issue by azoyan** [rsonquery/rsonpath#626]
To prevent loggins this:
```
[2024-12-27T08:43:19Z INFO  rsonpath::engine::main] SIMD configuration:
     avx2;fast_quotes;fast_popcnt
[2024-12-27T08:43:19Z INFO  rsonpath::engine::main] SIMD configuration:
     avx2;fast_quotes;fast_popcnt
```

**Comment by V0ldek** [comment]
I don't get this one. `rsonpath-lib` just uses `log`, we don't override any configurations.

If you're using [`env-logger`](https://docs.rs/env_logger/latest/env_logger/) in your project you can tell it to silence our logs with the env variable:

```
RUST_LOG="info,rsonpath=warn"
```
